server.port: 9090

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: user
      password: 1234

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # sql문 pretty하게 보여줌
        use_sql_comments: true
    generate-ddl: true   # true, false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none    # create, create-drop, update, validate, none


  sql:
    init:
      mode: never # never, always
      # always: embeded db가 아닌 외부 db 사용 시 spring boot를 실행할때 마다 data.sql schema.sql import.sql을 항상 실행
      # never: data.sql schema.sql import.sql을 실행하지 않음
      encoding: utf-8

  h2:
    console:
      path: /h2-console
      enabled: true

  datasource:
    #    url: jdbc:mariadb://ec2-3-34-177-39.ap-northeast-2.compute.amazonaws.com/mydb         # mariadb
    url: jdbc:mariadb://localhost:3306/mydb         # mariadb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 1234


  devtools:
    livereload:
      enabled: true

app:
  file-upload-path: /images
